# YCSB is part of redis-server, not a separate shared library.
all:
	$(MAKE) -C ../src redis-server

clean:
	$(RM) ../src/ycsb.o ../src/ycsb.d ../src/ycsb_core_workload.o ../src/ycsb_core_workload.d

.PHONY: all clean


